2024-09-22 18:11:27,296 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:13:52,137 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:13:52,339 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:13:52,340 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:13:52,387 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:13:52,464 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:13:52,584 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:13:52,621 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:13:52,703 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:13:52,729 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:23:48,706 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:23:48,706 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:23:48,707 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-22 18:23:48,994 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:23:48,995 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:23:48,995 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-22 18:23:49,074 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:23:49,076 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-22 18:23:49,079 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-23 17:27:43,822 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-23 17:27:43,823 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-24 09:20:17,152 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-24 09:20:17,403 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-24 09:20:17,437 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-24 09:23:48,911 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-24 09:23:48,995 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-24 09:23:49,030 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-24 09:34:26,083 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:156]
2024-09-24 09:34:26,084 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:166]
2024-09-24 09:36:08,097 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:156]
2024-09-24 09:36:08,097 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:166]
2024-09-24 09:42:33,240 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:156]
2024-09-24 09:42:33,240 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:166]
2024-09-24 09:42:51,141 - app - INFO - Cargando datos del usuario: edefrutos [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:156]
2024-09-24 09:42:51,141 - app - INFO - Mostrando imagen de perfil para el usuario edefrutos: f04e2644614b7ed0.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:166]
2024-09-24 11:02:46,350 - app - ERROR - Exception on /reset_password [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 178, in reset_request
    send_reset_email(user)
  File "/home/ec2-user/aws_edfcatalogoqr/app/utils.py", line 155, in send_reset_email
    token = user.get_reset_token()
  File "/home/ec2-user/aws_edfcatalogoqr/app/models.py", line 66, in get_reset_token
    return s.dumps({'user_id': str(self.id)})  # Eliminar .decode('utf-8')8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/serializer.py", line 317, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/timed.py", line 51, in sign
    return value + sep + self.get_signature(value)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 218, in get_signature
    key = self.derive_key()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 204, in derive_key
    bytes, self.digest_method(self.salt + b"signer" + secret_key).digest()
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
2024-09-24 18:22:49,393 - app.routes - INFO - Nombre original normalizado: Contenedor - 06 [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:343]
2024-09-24 18:22:49,395 - app.routes - INFO - Nuevo nombre normalizado: Contenedor - 06 [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:344]
2024-09-24 18:22:49,395 - app.routes - INFO - Imágenes recibidas: [<FileStorage: 'imagen01.jpg' ('image/jpeg')>] [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:355]
2024-09-24 18:22:49,459 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/aws_edfcatalogoqr/app/static/container_pics/ed703e4724027047.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/utils.py:108]
2024-09-24 18:22:49,482 - app.routes - INFO - Contenedor 66c632a9ebcf2e46db544a11 guardado exitosamente. [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:369]
2024-09-24 18:28:14,496 - app.routes - INFO - Creación de contenedor iniciada. [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:235]
2024-09-24 18:28:14,554 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/aws_edfcatalogoqr/app/static/container_pics/b408df5dccffae7f.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/utils.py:108]
2024-09-24 18:28:14,591 - app.routes - INFO - Contenedor creado con ID: 66f304be6795d6104c0d1974 [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:276]
2024-09-24 18:29:05,321 - app.routes - INFO - Nombre original normalizado: Nombre [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:343]
2024-09-24 18:29:05,321 - app.routes - INFO - Nuevo nombre normalizado: Nombre [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:344]
2024-09-24 18:29:05,321 - app.routes - INFO - Imágenes recibidas: [<FileStorage: '20030606_065302_05.jpg' ('image/jpeg')>] [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:355]
2024-09-24 18:29:05,379 - app.utils - INFO - Imagen del contenedor guardada en: /home/ec2-user/aws_edfcatalogoqr/app/static/container_pics/9e23ed68a43b1b0e.jpg [in /home/ec2-user/aws_edfcatalogoqr/app/utils.py:108]
2024-09-24 18:29:05,398 - app.routes - INFO - Contenedor 66f304be6795d6104c0d1974 guardado exitosamente. [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:369]
2024-09-24 18:29:30,444 - app.routes - INFO - Nombre original normalizado: Ar4chivador de plastico [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:343]
2024-09-24 18:29:30,444 - app.routes - INFO - Nuevo nombre normalizado: Archivador de plastico [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:344]
2024-09-24 18:29:30,445 - app.routes - INFO - El nombre del contenedor ha cambiado, verificando si ya está en uso. [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:348]
2024-09-24 18:29:30,457 - app.routes - INFO - Imágenes recibidas: [<FileStorage: '' ('application/octet-stream')>] [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:355]
2024-09-24 18:29:30,474 - app.routes - INFO - Contenedor 66d1f6788859808b0cfd6f5e guardado exitosamente. [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:369]
2024-09-24 18:54:46,421 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-24 18:54:46,504 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:23]
