2024-09-20 21:18:12,995 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:20:25,020 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:20:25,162 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:20:25,164 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:21:45,954 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:30:19,949 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:30:19,997 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:30:20,123 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:30:20,218 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:30:20,240 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:30:20,318 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:30:20,337 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:30:20,345 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:30:20,398 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:44:00,447 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:44:00,565 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:44:00,600 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:44:00,714 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:44:00,805 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:44:00,818 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:44:00,838 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:44:00,893 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:44:00,907 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:45:17,918 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:45:17,996 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:45:18,033 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:46:19,357 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:46:19,443 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:46:19,542 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:46:19,596 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:46:19,698 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:46:19,699 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:46:19,757 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:46:19,762 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:46:19,810 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:49:06,182 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:49:06,290 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:49:06,326 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:55:19,229 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:55:19,444 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:55:19,519 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:55:19,525 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:55:19,550 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:55:19,787 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:55:19,802 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:55:19,871 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:55:19,885 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:56:10,331 - app - ERROR - Exception on /reset_password [POST] [in /home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/aws_edfcatalogoqr/app/routes.py", line 171, in reset_request
    send_reset_email(user)
  File "/home/ec2-user/aws_edfcatalogoqr/app/utils.py", line 155, in send_reset_email
    token = user.get_reset_token()
  File "/home/ec2-user/aws_edfcatalogoqr/app/models.py", line 66, in get_reset_token
    return s.dumps({'user_id': str(self.id)})  # Eliminar .decode('utf-8')8')
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/serializer.py", line 317, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/timed.py", line 51, in sign
    return value + sep + self.get_signature(value)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 218, in get_signature
    key = self.derive_key()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/itsdangerous/signer.py", line 204, in derive_key
    bytes, self.digest_method(self.salt + b"signer" + secret_key).digest()
TypeError: unsupported operand type(s) for +: 'int' and 'bytes'
2024-09-20 21:56:45,737 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:56:45,942 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:56:45,949 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:56:45,956 - app - INFO - Aplicación Flask iniciada correctamente [in /home/ec2-user/aws_edfcatalogoqr/app/__init__.py:70]
2024-09-20 21:56:46,075 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:56:46,210 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:56:46,211 - app.models - INFO - Desconexión exitosa de la base de datos anterior. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:26]
2024-09-20 21:56:46,289 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-20 21:56:46,297 - app.models - INFO - Conectado a la base de datos. [in /home/ec2-user/aws_edfcatalogoqr/app/models.py:33]
2024-09-21 09:34:21,936 - app - INFO - Cargando datos del usuario: Sergio [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:150]
2024-09-21 09:34:21,936 - app - INFO - Mostrando imagen de perfil para el usuario Sergio: ad99bc63a5516605.png [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:157]
2024-09-21 09:36:15,494 - app.routes - INFO - Imágenes recibidas: [<FileStorage: '6DFF5AEC-F354-48B9-B374-A572C0329A8E.jpeg' ('image/jpeg')>] [in /home/ec2-user/aws_edfcatalogoqr/app/routes.py:298]
